# Generated by Django 4.0.1 on 2022-02-07 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('username', models.CharField(max_length=100000, primary_key=True, serialize=False, verbose_name='Enter username')),
                ('password', models.CharField(max_length=20, verbose_name='Enter Password')),
            ],
        ),
        migrations.CreateModel(
            name='Hash_key',
            fields=[
                ('hash_username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Visalization.registration')),
                ('user_key', models.CharField(max_length=256)),
            ],
        ),
    ]
