# Generated by Django 4.0.1 on 2022-02-14 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visalization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uni_analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=10000000000000000000)),
                ('name', models.CharField(max_length=10000000000000000000)),
            ],
        ),
    ]
